group = "com.golrang.map_kit"
version = "1.0-SNAPSHOT"

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://maven.neshan.org/artifactory/public-maven"
            content {
                includeGroup "neshan-android-sdk"
            }
        }
    }
}

apply plugin: "com.android.library"

android {
    if (project.android.hasProperty("namespace")) {
        namespace = "com.golrang.map_kit"
    }

    compileSdk = 36

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlin {
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
        }
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
        test.java.srcDirs += "src/test/kotlin"
    }

    defaultConfig {
        minSdk = 21
        consumerProguardFiles("proguard-rules.pro")
    }


    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
        }
    }


    dependencies {
        testImplementation("org.jetbrains.kotlin:kotlin-test")
        testImplementation("org.mockito:mockito-core:5.0.0")

        implementation 'androidx.appcompat:appcompat:1.6.1'
        implementation 'com.google.android.material:material:1.8.0'

        implementation 'androidx.core:core-ktx:1.9.0'

        implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

        implementation 'neshan-android-sdk:mobile-sdk:1.0.3'
        implementation 'neshan-android-sdk:services-sdk:1.0.0'
        implementation 'neshan-android-sdk:common-sdk:0.0.3'

        //Play Services
        implementation 'com.google.android.gms:play-services-gcm:16.1.0'
        implementation 'com.google.android.gms:play-services-location:17.0.0'

    }

    testOptions {
        unitTests.all {
            useJUnitPlatform()

            testLogging {
                events "passed", "skipped", "failed", "standardOut", "standardError"
                outputs.upToDateWhen { false }
                showStandardStreams = true
            }
        }
    }
}
